export const CONTEMBER_CONTENT_URL = process.env.CONTEMBER_CONTENT_URL
export const CONTEMBER_TENANT_URL = process.env.CONTEMBER_TENANT_URL
export const CONTEMBER_TOKEN = process.env.CONTEMBER_TOKEN
export const EMAIL_HOST = process.env.EMAIL_HOST
export const EMAIL_PORT = parseInt(process.env.EMAIL_PORT, 10)
export const EMAIL_USER = process.env.EMAIL_USER
export const EMAIL_PASSWORD = process.env.EMAIL_PASSWORD
export const EMAIL_FROM = process.env.EMAIL_FROM
export const FRONTEND_URL = process.env.FRONTEND_URL
export const TYPESENSE_HOST = process.env.TYPESENSE_HOST
export const TYPESENSE_PORT = parseInt(process.env.TYPESENSE_PORT, 10)
export const TYPESENSE_PROTOCOL = process.env.TYPESENSE_PROTOCOL
export const TYPESENSE_API_KEY = process.env.TYPESENSE_API_KEY
export const TYPESENSE_HOST_PUBLIC = process.env.TYPESENSE_HOST_PUBLIC
export const TYPESENSE_PORT_PUBLIC = parseInt(process.env.TYPESENSE_PORT_PUBLIC, 10)
export const TYPESENSE_PROTOCOL_PUBLIC = process.env.TYPESENSE_PROTOCOL_PUBLIC
export const TYPESENSE_API_KEY_PUBLIC = process.env.TYPESENSE_API_KEY_PUBLIC
