name: 'Test and Deploy'

on:
  push:
    branches:
      - main
      - 'deploy/*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::831119889470:role/github_deploy_production
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          file: Dockerfile
          tags: |
            831119889470.dkr.ecr.eu-central-1.amazonaws.com/mangoweb/app/ukrajina/worker:gh-${{ github.sha }}
